version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: soltty
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/torreirow/soltty/cmd.version={{.Version}}
    binary: soltty-{{.Os}}-{{.Arch}}

archives:
  - name_template: "soltty-{{.Version}}-{{.Os}}-{{.Arch}}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: torreirow
    name: soltty
